### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by incubos** [Noxoomo/DBCSC#2]
``` shell
$ sbt test
[info] Loading project definition from /Users/incubos/devel/hw/DBCSC/project
[info] Set current project to DBCSC (in build file:/Users/incubos/devel/hw/DBCSC/)
[info] Compiling 2 Scala sources to /Users/incubos/devel/hw/DBCSC/target/scala-2.10/test-classes...
no db found, creating new Database
[info] DatabaseTest:
[info] Database
[info] - should start with empty file *** FAILED ***
[info]   server.Exception.DatabaseNotStartedException:
[info]   at server.Database.add(Database.scala:18)
[info]   at server.DatabaseTest$$anonfun$1.apply$mcV$sp(DatabaseTest.scala:21)
[info]   at server.DatabaseTest$$anonfun$1.apply(DatabaseTest.scala:18)
[info]   at server.DatabaseTest$$anonfun$1.apply(DatabaseTest.scala:18)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info] Database
[info] - should implement CRUD *** FAILED ***
[info]   server.Exception.DatabaseNotStartedException:
[info]   at server.Database.get(Database.scala:68)
[info]   at server.DatabaseTest$$anonfun$2.apply$mcV$sp(DatabaseTest.scala:37)
[info]   at server.DatabaseTest$$anonfun$2.apply(DatabaseTest.scala:33)
[info]   at server.DatabaseTest$$anonfun$2.apply(DatabaseTest.scala:33)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info] Database
[info] - should recover from commit log *** FAILED ***
[info]   server.Exception.DatabaseNotStartedException:
[info]   at server.Database.get(Database.scala:68)
[info]   at server.DatabaseTest$$anonfun$3.apply$mcV$sp(DatabaseTest.scala:53)
[info]   at server.DatabaseTest$$anonfun$3.apply(DatabaseTest.scala:48)
[info]   at server.DatabaseTest$$anonfun$3.apply(DatabaseTest.scala:48)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info] ServerTest:
[info] Server
[info] - should start database and process queries
[info] Run completed in 278 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 1, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error]     server.DatabaseTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed 23.09.2013 17:32:01
```

**Comment by Noxoomo** [comment]
fixed
