### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by incubos** [Noxoomo/DBCSC#6]
Master branch should be green:

``` shell
$ sbt test
[info] Loading project definition from /Users/incubos/devel/hw/Noxoomo/DBCSC/project
[info] Set current project to DBCSC (in build file:/Users/incubos/devel/hw/Noxoomo/DBCSC/)
[info] BigDataTest:
[info] - should handling big data !!! IGNORED !!!
[info] ServerTest:
[info] Server
[info] - should start database and process queries
Actor[akka://NodeTest/user/$a#2094414659]
Actor[akka://RouterTest/user/$b#1554011918]
Actor[akka://RouterTest/user/$a#-2124009651]
Actor[akka://RouterTest/user/$c#841557529]
Actor[akka://NodeTest/user/$a#2057336247]
[INFO] [10/13/2013 00:43:23.165] [RouterTest-akka.actor.default-dispatcher-7] [akka://RouterTest/user] Message [client.Messages$OK] from Actor[akka://RouterTest/user/router#-3464887] to Actor[akka://RouterTest/user] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [10/13/2013 00:43:23.166] [RouterTest-akka.actor.default-dispatcher-7] [akka://RouterTest/user] Message [client.Messages$OK] from Actor[akka://RouterTest/user/router#-3464887] to Actor[akka://RouterTest/user] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [10/13/2013 00:43:23.166] [RouterTest-akka.actor.default-dispatcher-7] [akka://RouterTest/user] Message [client.Messages$OK] from Actor[akka://RouterTest/user/router#-3464887] to Actor[akka://RouterTest/user] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] RouterTest:
[info] An router actor
[info] - must router message to 3 nodes
4354[info] DiskStorageTest:
[info] DiskStorage
[info] - should create OnDiskStorage and implement CRUD
[info] DiskStorage
[info] - should pass stress-test
[info] DiskStorage
[info] - should recover from commit-log and merge *** FAILED ***
[info]   java.nio.file.NoSuchFileException: src/test/resources/testDiskStorageRecover/1381328478565
[info]   at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[info]   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[info]   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[info]   at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:520)
[info]   at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:252)
[info]   at java.nio.file.Files.copy(Files.java:1225)
[info]   at Utils.FileUtils$.copyFile(FileUtils.scala:46)
[info]   at server.DiskStorageTest$$anonfun$3.apply$mcV$sp(DiskStorageTest.scala:60)
[info]   at server.DiskStorageTest$$anonfun$3.apply(DiskStorageTest.scala:54)
[info]   at server.DiskStorageTest$$anonfun$3.apply(DiskStorageTest.scala:54)
[info]   ...
[info] DiskStorage
[info] - should read from existing Database *** FAILED ***
[info]   NothingFound() was not equal to Value(value1) (DiskStorageTest.scala:79)
[info] NodesTest:
[info] Nodes
[info] - should start and proceed queries *** FAILED ***
[info]   NoKey(key1,1) was not equal to Answer(key1,value1,1) (NodesTest.scala:34)
[info] Nodes
[info] - should pass stress-test
[INFO] [10/13/2013 00:44:10.631] [NodeTest-akka.actor.default-dispatcher-5] [akka://NodeTest/deadLetters] Message [client.Messages$GetClose] from Actor[akka://NodeTest/user/$a#2057336247] to Actor[akka://NodeTest/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] Run completed in 48 seconds, 135 milliseconds.
[info] Total number of tests run: 8
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 5, failed 3, canceled 0, ignored 1, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error]     server.DiskStorageTest
[error]     distributed.NodesTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 49 s, completed 13.10.2013 0:44:10
```

**Comment by Noxoomo** [comment]
forgot to commit  test data, fixed
Should i remove ignore test (yellow)? (test with 16M keys)
