### ISSUE TITLE
OOM when running BigDataTest

### ISSUE THREAD

**Issue by incubos** [Noxoomo/DBCSC#7]
The stack trace:

``` java
An exception or error caused a run to abort: Java heap space 
java.lang.OutOfMemoryError: Java heap space
    at java.util.TimSort.ensureCapacity(TimSort.java:902)
    at java.util.TimSort.mergeLo(TimSort.java:655)
    at java.util.TimSort.mergeAt(TimSort.java:483)
    at java.util.TimSort.mergeCollapse(TimSort.java:410)
    at java.util.TimSort.sort(TimSort.java:214)
    at java.util.TimSort.sort(TimSort.java:173)
    at java.util.Arrays.sort(Arrays.java:659)
    at scala.collection.SeqLike$class.sorted(SeqLike.scala:615)
    at scala.collection.mutable.ArrayOps$ofRef.sorted(ArrayOps.scala:108)
    at scala.collection.SeqLike$class.sortBy(SeqLike.scala:594)
    at scala.collection.mutable.ArrayOps$ofRef.sortBy(ArrayOps.scala:108)
    at server.OnDiskStorage.FileIndex$.index(FileIndex.scala:59)
    at server.OnDiskStorage.DiskStorageMaintains.garbageCollect(DiskStorageMaintains.scala:86)
    at server.OnDiskStorage.DiskStorage.<init>(DiskStorage.scala:24)
    at server.BigDataTest$$anonfun$1.apply$mcV$sp(BigDataTest.scala:18)
    at server.BigDataTest$$anonfun$1.apply(BigDataTest.scala:15)
    at server.BigDataTest$$anonfun$1.apply(BigDataTest.scala:15)
    at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1617)
    at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
    at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1497)
    at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1614)
    at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1626)
    at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1626)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1626)
    at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1497)
```

**Comment by Noxoomo** [comment]
strange, on my laptop with -Xmx1g worked fine (java version "1.7.0_13"), reduce dump size, now should use less memory

**Comment by Noxoomo** [comment]
tested it again: takes ≈ 18 minutes to add data, ≈ 10 minutes to read all keys (ssd)

**Comment by Noxoomo** [comment]
Did you run test more than once? I forgot to clean data before starting test. From crashlog it looks like it happens during creating index of ≈16G file (so index size ≈200M). My current index need memory to read and sort for all keys hash+offset (12 bytes per key) data in memory before running.  
I wrote sorting index in files, after checking it can enable it by defualt

**Comment by Noxoomo** [comment]
hybrid index sorting — if keys < 500000 => sort in memory, else merge sort on files + indexTest on 1M keys
if OOM still exists, reopen issue
